config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :bookings, except: [:index, :new]
  resources :chefs
  resources :reviews, only: [:create, :new, :destroy, :edit, :show, :update]
  # get 'messages/show'
  devise_for :users
  get 'users/home', to: 'users#home'
  get 'users/:id', to: 'users#show'
  # get 'users/edit', to: 'users#edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/chef.rb
class Chef < ApplicationRecord
    belongs_to :user
    has_many :messages
    has_many :bookings
    has_many :reviews, through: :bookings
    validates :description, :cuisine, :location_range, :price, :chef_postcode, presence: :true
    has_many_attached :photos
    max_paginates_per 24


end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  def index
    @chefscount = Chef.all
    # @chefs = Chef.order(:name).page params[:page]
    if params[:query].present?
      sql_query = " \
        chefs.description ILIKE :query \
        OR chefs.cuisine ILIKE :query \
        OR users.first_name ILIKE :query \
        OR users.last_name ILIKE :query \
      "
      @chefs = Chef.joins(:user).where(sql_query, query: "%#{params[:query]}%").order(created_at: :desc).page(params[:page])
    else
      @chefs = Chef.order(created_at: :desc).page(params[:page]).limit(20)
    end
  end

  def show
    @chefs = Chef.all.sample(3)
    @chef = Chef.find(params[:id])
    @booking = Booking.new
    counter = 0
    reviews = 0
    @chef.bookings.each do |b|
      if b.review
      counter += b.review.rating.to_i
      reviews += 1
      end
    end
    if counter > 0
      rating = counter/reviews

    else rating = 0
    end
    @chef.rating = rating
    @chef.save
  end

  def new
    @chef = Chef.create
  end

  def create
    @chef = Chef.new(chef_params)
    current_user.is_a_chef = true
    current_user.save
    @chef.user = current_user
    @chef.save
    if @chef.save
        redirect_to root_path
      else
        render :new
      end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  private

  def chef_params
    params.require(:chef).permit(:description, :cuisine, :location_range, :price, :chef_postcode, photos: [])
  end



end

app/views/chefs/_form.html.erb
<%= simple_form_for [@booking, @chef] do |f|%>
  <%= f.input :price %>
  <%= f.submit %>
<% end %>

app/views/chefs/create.html.erb
<h1>Chefs#create</h1>
<p>Find me in app/views/chefs/create.html.erb</p>

app/views/chefs/destroy.html.erb
<h1>Chefs#destroy</h1>
<p>Find me in app/views/chefs/destroy.html.erb</p>

app/views/chefs/edit.html.erb
<h1>Chefs#edit</h1>
<p>Find me in app/views/chefs/edit.html.erb</p>

app/views/chefs/index.html.erb
<div class="container">
    <h2 class="mt-4">Chefs near you</h2>
    <p><%=@chefs.count%> results</p>
    <p><strong>💥 Your dinner is in 14 days.</strong> We're normally booked out by now</p>
    <div class="cards pt-3">
        
        <% @chefs.each do |chef| %>	

            <div class="card-trip-index">
                <% if chef.photos[0].present? %>
                    <%=  cl_image_tag chef.photos[0].key %>
                <% else %>
                    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
                <% end %>
                <div class="card-trip-infos">
                    <div>
                    <h2><%= link_to "#{chef.user.first_name} #{chef.user.last_name}", chef_path(chef) %></h2>
                    <p> Cuisine |  <%= chef.cuisine %> <br>
                        <% if chef.rating %>
                            <% chef.rating.times do  %>
                                <span>★</span>
                            <% end %>
                        <% end %>
                    </p>	
                    </div>
                    <h2 class="card-trip-pricing">£ <%=chef.price%></h2>
                    <% if chef.user.photo.attached? %>
                        <%=  cl_image_tag chef.user.photo.key, :gravity=>"faces", :width=>42, :height=>42, :crop=>"fill", class: "card-trip-user avatar-bordered" %>
                    <% else %>
                        <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
                    <% end %>
                </div>
            </div>

        <% end %>	
    </div>
    <div class="d-flex justify-content-center mt-4">
        <div class="d-flex flex-column">
        <div class="p-2 text-center">
            <%= page_entries_info @chefs %>
        </div>
        <div class="p-2">
            <%= paginate @chefs %>
        </div>
        
        </div>
    
    </div>

</div>

app/views/chefs/new.html.erb
<div class="container">
  <div class="text-center my-4">
    <h1>Sign up as chef!</h1>
    <p>Think of the £££</p>
  </div>
  <div class="d-flex justify-content-center">
    <div class="w-50">
      <%= simple_form_for @chef do |f| %>
        <%= f.input :cuisine %>
        <%= f.input :description, as: :text %>
        <%= f.input :chef_postcode %>
        <%= f.input :price %>
        <%= f.input :location_range %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.button :submit, class: "btn btn-primary"%>
      <% end %>
    </div> 
  </div>
</div>

app/views/chefs/show.html.erb
<div class="container">
  <h2 class= "mt-3"> <%= @chef.user.first_name %> <%= @chef.user.last_name %> </h2>
  <p>
  <% @chef.rating.times do  %>
    <span>★</span>
  <% end %> -- Location: <%= @chef.chef_postcode %></p>



    <div class="main-image-container">
      <div class="left-main-image-container">
       <% if @chef.photos[0].present? %>
        <%= cl_image_tag @chef.photos[0].key, alt: "alttext", class: 'image-main-large'%>
       <% else %>
        <%= image_tag "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=953&q=80", alt: "alttext", class: 'image-main-large'%>
       <% end %>
      </div>
      <div class="right-main-image-container">
        <% if @chef.photos[1].present? %>
          <%= cl_image_tag @chef.photos[1].key, alt: "alttext", class: 'image-main-small'%>
        <% else %>
          <%= image_tag "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60", alt: "alttext", class: 'image-main-small'%>
        <% end %>
        <% if @chef.photos[2].present? %>
          <%= cl_image_tag @chef.photos[2].key, alt: "alttext", class: 'image-main-small'%>
        <% else %>
          <%= image_tag "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60", alt: "alttext", class: 'image-main-small'%>
        <% end %>
      </div>
    </div>



  <div class="container">
   <div class="row justify-content-end mt-5">
    <div class="col-8 p-0">
     <div class="d-flex justify-content-between">
       <div class="ml-0">
        <h3>Chef Summary</h3>
         <p>  <%= @chef.description.truncate(200) %> </p>
       </div>
        <% if @chef.user.photo.attached? %>
            <%=  cl_image_tag @chef.user.photo.key, class: "avatar-large-chef mb-2" %>
        <% else %>
            <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg", class="avatar" />
        <% end %>
      </div>
       <hr class="featurette-divider">
      <h3>Cuisine</h3>
      <p> <%= @chef.cuisine %></p>
      <hr class="featurette-divider">
    </div>
    <div class="col-4 pr-0">
      <div class = "card shadow p-3 mb-5 bg-white rounded price-box">
        <h4><strong> £</strong><strong class="price-per-person"><%= @chef.price %></strong> / per guest</h4>
        <p> - - - - - - - - - - - -  - - -</p>
        <%= simple_form_for @booking do |f|%>
          <%= f.input :date, as: :datetime, html5: true %>
        <div class="form-group">
          <label for="exampleFormControlSelect1">Number of Guests:</label>
          <select class="form-control guests" id="scripts">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
            <option>6</option>
            <option>7</option>
            <option>8</option>
            <option>9</option>
            <option">10</option>
            <option">11</option>
            <option">12</option>
          </select>
        </div>
          <%= f.hidden_field :price, value: @chef.price %>
          <%= f.hidden_field :chef_id, value: @chef.id %>
          <%= f.button :submit, class: "d-none", id: "confirm-booking" %>
        <% end %>
        <% if current_user %>
        <button id="sweet-alert-demo" class="btn btn-primary">Create Booking </button>
        <% else %>
        <%= link_to 'Please Sign-up/Login', new_registration_path(User.new), class: "btn btn-primary" %>
        <% end %>
        <div id="total-price"></div>
    </div>
  </div>

 <hr class="featurette-divider">

  <div class="container reviews p-0">
  <% if @chef.bookings.count > 0 %>
    <h3>Reviews For <%= @chef.user.first_name %> <%= @chef.user.last_name %></h3>
    <% @chef.bookings.each do |b| %>
      <% if b.review.rating %>
      <div class="review my-3 p-3">
        <p><%= b.review.content %></p>
        
        <% if  b.review.rating %>
        <p>Rating: <% b.review.rating.times do  %><span>★</span><% end %></p>
        <% end %>
        <p><strong>- <%= b.user.first_name %> <%= b.user.last_name %></strong></p>
      </div>
        <% end %>
    <% end %>
  <% else %>
    <h3>Reviews</h3>
    <p>There are currently no reviews for this Chef</p>
  <% end %>
  <a class="btn btn-primary p-2"href="/chefs">Return to 'Browse Chefs'</a>
  <hr class="featurette-divider">
  <div class="featured-chef-container">
    <h3>Other Chefs you may be interested in....</h3>
  <div class="row justify-content-center flex-wrap" id="chef" style="margin-top: 32px;">
    <% @chefs.each do |chef| %>
    <div class="m-1 col-lg feature-chef-card justify-content-center">
      <% if chef.user.photo.attached? %>
        <%= cl_image_tag chef.user.photo.key, :gravity=>"faces", :crop=>"fill", class: "avatar-bordered feature-avatar m-1", alt: "avatar-large" %>
      <% else %>
        <%= image_tag "https://cdn.shopify.com/s/files/1/0026/1740/9636/files/iStock-690837852_large.jpg?v=1543101282", class: "avatar-bordered feature-avatar m-1", alt: "avatar-large" %>
      <% end %>
     <h2><%= chef.user.first_name %> <%= chef.user.last_name %></h2>
      <div>
        <p><%= chef.description.truncate(200) %></p>
      </div>
      <p><%= link_to "View Chef", chef_path(chef), class:"btn btn-secondary" %></p>
    </div><!-- /.col-lg-4 -->
    <% end %>
  </div>
  </div>
</div>
</div>
</div>

app/views/chefs/update.html.erb
<h1>Chefs#update</h1>
<p>Find me in app/views/chefs/update.html.erb</p>