config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :bookings, except: [:index, :new]
  resources :chefs
  resources :reviews, only: [:create, :new, :destroy, :edit, :show, :update]
  # get 'messages/show'
  devise_for :users
  get 'users/home', to: 'users#home'
  get 'users/:id', to: 'users#show'
  # get 'users/edit', to: 'users#edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :reviews, through: :bookings
  has_many :messages
  has_one :chef
  has_one :chef, dependent: :destroy
  has_one_attached :photo
  validates :first_name, :last_name, :phone_number, :address, :postcode, presence: :true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   raise
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)

  #     super(resource)

  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
  end

  def new
  end

  def show
    @user = User.find(params[:id])
  end

  def home
    @bookings = Booking.where(user: current_user)
    @past_bookings = @bookings.where("date < ?", DateTime.now) 
    @future_bookings = @bookings.where("date > ?", DateTime.now) 

    @chef_bookings = Booking.where(chef: current_user.chef)
    @past_chef_bookings = @chef_bookings.where("date < ?", DateTime.now) 
    @future_chef_bookings = @chef_bookings.where("date > ?", DateTime.now) 
  end

  def index
    @chefs = User.where(is_a_chef: true)
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def user_params
    params.require(:cocktail).permit(:first_name, :last_name, :address, :postcode, :email, :password, :phone_number, :photo)
  end

end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<% if current_user.is_a_chef == false %>
  <h1>Your details</h1>
  <p>details here</p>
  <p>edit details btn</p>

  <h3>Reviews given</h3>
<% else %>
  <h1>Your details</h1>
  <p>user details here</p>
  <p>chef details here</p>
  <p>view chef profile btn</p>
  <p>edit chef details btn</p>
  <p>Your rating</p>
  <p>your reviews</p>
<% end %>

app/views/users/home.html.erb
<div class="container">
  <div class="user-profile-card d-flex flex-wrap justify-content-start align-items-start">
    <div>
      <h2>
      <%= current_user.first_name %>
      <%= current_user.last_name %>
      </h2>

      <% if current_user.photo.attached? %>
      <%= cl_image_tag current_user.photo.key, class: "avatar-bordered feature-avatar" %>
      <% end %>
      <p class="mt-3"><i class="fas fa-pencil-alt text-muted"></i> <%= link_to "Edit your profile", edit_user_registration_path(current_user) %></p>
      <p></p>
    </div>
    <div class="p-5">
    <p>Member since <%= current_user.created_at.strftime("%B %e %Y") %></p>
    <p>Total bookings: <%= current_user.bookings.count %></p>
    <% if current_user.bookings.count > 0 %>
    <p>First booking: <%= current_user.bookings.first.date.strftime("%B %e %Y") %> with <%= current_user.bookings.first.chef.user.first_name %> <%= current_user.bookings.first.chef.user.last_name %></p>

    <p>Latest booking: <%= current_user.bookings.last.date.strftime("%B %e %Y") %> with <%= current_user.bookings.last.chef.user.first_name %> <%= current_user.bookings.last.chef.user.last_name %></p>
    <% else %>
    <p><%= link_to "Make your first booking", chefs_path, class: "btn btn-primary" %></p>
    <% end %>
    </div>
  </div>

  <div>
  <% if current_user.is_a_chef  %>


  <% @chef_bookings.each do |b| %>
  <h4><%= b.date.strftime("%B %e %Y") %> - <%= b.user.first_name%> <%= b.user.last_name%></h4>

  <% end %>

  <% elsif @bookings %>


  <% if @future_bookings.empty? %>
    <h3 class="mt-3">You have no upcoming bookings.</h3>
    <p><%= link_to "View all chefs", chefs_path, class: "btn btn-primary" %></p>
  <% else %>
    <h3 class="mt-3">Upcoming Bookings</h3>
    <% @future_bookings.each do |b| %>
    <div class="card-trip m-1">
      <h2 class="p-1"><%= b.date.strftime("%B %e %Y") %></h2>
      <% if b.chef.photos.present? %>
      <%= cl_image_tag b.chef.photos[0].key %>
      <% else %>
      <%= image_tag "https://images.unsplash.com/photo-1537815749002-de6a533c64db?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1445&q=80", alt: "cute dog" %>
      <% end %>

      <div class="card-trip-infos">
        <div>
          
          <h2><%= b.chef.user.first_name %> <%= b.chef.user.last_name %></h2>
          <p><%= b.chef.description %></p>
        </div>

        <h2 class="card-trip-pricing">£<%= b.chef.price %></h2>
        <% if b.chef.user.photo.present? %>
        <%= cl_image_tag b.chef.user.photo.key, class: "card-trip-user avatar-bordered" %>
        <% else %>
        <img src="https://images.unsplash.com/photo-1537815749002-de6a533c64db?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1445&q=80" class="card-trip-user avatar-bordered" alt="cute dog">
        <% end %>
      </div>
    </div>
  <% end %>

  <% unless @past_bookings.empty? %>
    <h3 class="mt-3">Past Bookings</h3>
    <% @past_bookings.each do |b| %>
    <div class="card-trip m-1">
      <h2 class="p-1"><%= b.date.strftime("%B %e %Y") %></h2>
      <% if b.chef.photos.present? %>
      <%= cl_image_tag b.chef.photos[0].key %>
      <% else %>
      <%= image_tag "https://images.unsplash.com/photo-1537815749002-de6a533c64db?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1445&q=80", alt: "cute dog" %>
      <% end %>

      <div class="card-trip-infos">
        <div>
          
          <h2><%= b.chef.user.first_name %> <%= b.chef.user.last_name %></h2>
          <p><%= b.chef.description %></p>
        </div>

        <h2 class="card-trip-pricing">£<%= b.chef.price %></h2>
        <% if b.chef.user.photo.present? %>
        <%= cl_image_tag b.chef.user.photo.key, class: "card-trip-user avatar-bordered" %>
        <% else %>
        <img src="https://images.unsplash.com/photo-1537815749002-de6a533c64db?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1445&q=80" class="card-trip-user avatar-bordered" alt="cute dog">
        <% end %>
      </div>
      
      <% if b.review.content.blank? %>
      <p class="text-right pr-2"><i class="fas fa-comments text-muted"></i> <%= link_to "Leave a review", edit_review_path(b.review) %></p>
      <% else %>
      <p class="text-left pl-3"><i class="fas fa-comments"></i> Your Review:</p>
      <p class="m-3"><%= b.review.content %></p>
      <p class="m-3"><% b.review.rating.times do  %><span>★</span><% end %></p>
      <% end %>
    </div>
  <% end %>

  <% end %>




  <% end %>

  <% end %>
  </div>

</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<ul>
<% @chefs.each do |chef|  %>

<li><%= chef.first_name %> <%= chef.last_name %> - <%= chef.chef.description %></li>

<% end %>

</ul>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<h1>This is the show page for
<%= @user.first_name %> 
<%= @user.last_name %> 
</h1>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>