config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :bookings, except: [:index, :new]
  resources :chefs
  resources :reviews, only: [:create, :new, :destroy, :edit, :show, :update]
  # get 'messages/show'
  devise_for :users
  get 'users/home', to: 'users#home'
  get 'users/:id', to: 'users#show'
  # get 'users/edit', to: 'users#edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
    <p>Made with 🧡 at Sumo Chef 👨‍🍳</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "" do %>

    <%= image_tag "Sumo2.jpg", size: "105x30"%>
    <% end %>
    <div class="form-inline">
      <%= form_tag chefs_path, method: :get do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a chef" %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>    
        <li class="nav-item dropdown">
          <% if current_user.photo.attached?%>
          <%= cl_image_tag current_user.photo.key, :gravity=>"faces", :width=>42, :height=>42, :crop=>"fill", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, crop: :fill %>
          <% else %>

            <%= image_tag 'avatar.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %> 

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "View Chefs", chefs_path, class: "dropdown-item" %>
            <% unless current_user.is_a_chef == true %>
              <%= link_to "Sign up as a chef", "/chefs/new", class: "dropdown-item" %>
            <% end %>
            <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Your bookings", users_home_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign-up", new_user_registration_path, class: "btn btn-primary" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>